/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integernumberarray;

/**
 *
 * @author Asus
 */
public class StatisticsView extends javax.swing.JFrame {
protected  IntegerArray array;
    /**
     * Creates new form StatisticsView
     */
    public StatisticsView() {
        initComponents();
        array = new IntegerArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStatistics = new javax.swing.JPanel();
        btnYoung = new javax.swing.JButton();
        btnOld = new javax.swing.JButton();
        btnMid = new javax.swing.JButton();
        btnGroups = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblYoung = new javax.swing.JLabel();
        lblOld = new javax.swing.JLabel();
        lblGroups = new javax.swing.JLabel();
        lblMid = new javax.swing.JLabel();
        lblStatistics = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Статистика за потребителите");
        setName("frmBase"); // NOI18N

        pnlStatistics.setBackground(new java.awt.Color(255, 170, 91));
        pnlStatistics.setForeground(new java.awt.Color(255, 170, 91));

        btnYoung.setBackground(new java.awt.Color(116, 255, 129));
        btnYoung.setText("Най-млад потребител");
        btnYoung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnYoungMouseClicked(evt);
            }
        });
        btnYoung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYoungActionPerformed(evt);
            }
        });

        btnOld.setBackground(new java.awt.Color(116, 255, 129));
        btnOld.setText("Най-възрастен потребител");
        btnOld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOldMouseClicked(evt);
            }
        });
        btnOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOldActionPerformed(evt);
            }
        });

        btnMid.setBackground(new java.awt.Color(116, 255, 129));
        btnMid.setText("Средна възраст на потребител");
        btnMid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMidMouseClicked(evt);
            }
        });
        btnMid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMidActionPerformed(evt);
            }
        });

        btnGroups.setBackground(new java.awt.Color(116, 255, 129));
        btnGroups.setText("Брой по възрастови групи");
        btnGroups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGroupsMouseClicked(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(178, 110, 46));
        btnExit.setText("Изход");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblStatistics.setText("Статистика за потребителите");

        javax.swing.GroupLayout pnlStatisticsLayout = new javax.swing.GroupLayout(pnlStatistics);
        pnlStatistics.setLayout(pnlStatisticsLayout);
        pnlStatisticsLayout.setHorizontalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisticsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlStatisticsLayout.createSequentialGroup()
                        .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnOld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnYoung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGroups, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYoung)
                            .addComponent(lblOld)
                            .addComponent(lblGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMid, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatisticsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(97, 97, 97))
        );
        pnlStatisticsLayout.setVerticalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYoung)
                    .addComponent(lblYoung))
                .addGap(1, 1, 1)
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOld)
                    .addComponent(lblOld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMid)
                    .addComponent(lblMid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGroups)
                    .addComponent(lblGroups))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYoungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYoungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYoungActionPerformed

    private void btnYoungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYoungMouseClicked
        
        int min = array.calcMin();
        lblYoung.setText(Integer.toString(min));
    }//GEN-LAST:event_btnYoungMouseClicked

    private void btnOldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOldMouseClicked
        int max = array.calcMax();
        lblOld.setText(Integer.toString(max));
    }//GEN-LAST:event_btnOldMouseClicked

    private void btnMidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMidMouseClicked
        int mid = array.calcMid();
        lblMid.setText(Integer.toString(mid));
    }//GEN-LAST:event_btnMidMouseClicked

    private void btnOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOldActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnGroupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGroupsMouseClicked
        int sum0_17 = array.byGroups(0,17);
        int sum18_24 = array.byGroups(18,24);
        int sum25_30 = array.byGroups(25,30);
        int sum31_35 = array.byGroups(31,35);
        int sum36_40 = array.byGroups(35,40);
        int sum41_45 = array.byGroups(41,45);
        int sum46_50 = array.byGroups(46,50);
        int sum51_55 = array.byGroups(51,55);
        int sum56_60 = array.byGroups(56,60);
        int sum61_70 = array.byGroups(61,70);
        int sum71_100 = array.byGroups(71,100);
        
        String txt ="<html> Под 18г.: " + Integer.toString(sum0_17);
        txt += "<br> 18 - 24г.: " + sum18_24;
        txt += "<br> 25 - 30г.: " + sum25_30;
        txt += "<br> 31 - 35г.: " + sum31_35;
        txt += "<br> 36 - 40г.: " + sum36_40;
        txt += "<br> 41 - 45г.: " + sum41_45;
        txt += "<br> 46 - 50г.: " + sum46_50;
        txt += "<br> 51 - 55г.: " + sum51_55;
        txt += "<br> 56 - 60г.: " + sum56_60;
        txt += "<br> 61 - 70г.: " + sum61_70;
        txt += "<br> Над 71г.: " + sum71_100 + "</html>";
        lblGroups.setText(txt);
    }//GEN-LAST:event_btnGroupsMouseClicked

    private void btnMidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGroups;
    private javax.swing.JButton btnMid;
    private javax.swing.JButton btnOld;
    private javax.swing.JButton btnYoung;
    private javax.swing.JLabel lblGroups;
    private javax.swing.JLabel lblMid;
    private javax.swing.JLabel lblOld;
    private javax.swing.JLabel lblStatistics;
    private javax.swing.JLabel lblYoung;
    private javax.swing.JPanel pnlStatistics;
    // End of variables declaration//GEN-END:variables
}
